spring:
  application:
    name: company-spring

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/company
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_JDBC_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DB_USER:myuser}
    password: ${SPRING_DB_PASSWORD:secret}


openapi:
  oauth:
    tokenUrl: http://localhost:8080/realms/company/protocol/openid-connect/token

springdoc:
  swagger-ui:
    oauth:
      client-id: company
      username: adam
      password: Benio111



server:
  port: ${SPRING_PORT:8081}
